import { Planet } from "../SolarSystem/planetTypes";

const planetsData: Planet[] = [
  {
    id: '1',
    name: 'Mercúrio',
    diameter: 4879,
    distance_from_sun: 57.9,
    orbital_period: 88,
    luas: 0,
    about: 'O planeta mais próximo do Sol, Mercúrio é um mundo extremo com temperaturas que variam drasticamente entre o dia e a noite.',
    color: '/textures/mercurio.jpg',
    temp:  -427,
    texturePath: '/textures/mercurio.jpg',
  },
  {
    id: '2',
    name: 'Vênus',
    about: 'Conhecido como a estrela da manhã, Vênus é o planeta mais quente do sistema solar devido ao seu efeito estufa extremo.',
    diameter: 12104,
    distance_from_sun: 108.2,
    orbital_period: 225,
    luas: 0,
    temp: 462,
    color: '/textures/venus.jpg',
    texturePath: '/textures/venus.jpg',
  },
  {
    id: '3',
    name: 'Terra',
    about: 'Nosso planeta natal, único conhecido por abrigar vida. A Terra possui água líquida em sua superfície e uma atmosfera rica em oxigênio.',
    diameter: 12742,
    distance_from_sun: 149.6,
    orbital_period: 365,
    luas: 1,
    temp: 58,
    color: '/textures/earthTerra.jpg',
    texturePath: '/textures/earthTerra.jpg',
  },
  {
    id: '4',
    name: 'Marte',
    about:'O Planeta Vermelho deve sua cor característica ao óxido de ferro em sua superfície. Marte possui as maiores montanhas do sistema solar.',
    diameter: 6779,
    distance_from_sun: 228,
    orbital_period: 687,
    luas: 2,
    temp: -5,
    color: '/textures/marte.jpg',
    texturePath: '/textures/marte.jpg',
  },
  {
    id: '5',
    name: 'Netuno',
    about: 'O planeta mais distante do Sol, Netuno é conhecido por seus ventos extremos que podem atingir 2.100 km/h.',
    diameter: 6779,
    distance_from_sun: 300,
    orbital_period: 687,
    luas: 16,
    temp: -201 ,
    color: '/textures/netuno.jpg',
    texturePath: '/textures/netuno.jpg',
  },
  {
    id: '6',
    name: 'Júpiter',
    about: 'O maior planeta do sistema solar, Júpiter é um gigante gasoso que protege os planetas interiores de asteroides e cometas.',
    diameter: 679,
    distance_from_sun: 250,
    orbital_period: 4333,
    luas: 95,
    temp: -108,
    color: '/textures/jupiter.jpg',
    texturePath: '/textures/jupiter.jpg',
  },
  {
    id: '7',
    name: 'Saturno',
    about: 'Famoso por seus espetaculares anéis, Saturno é o segundo maior planeta e tem densidade menor que a água.',
    texturePath: '/textures/saturn.jpg',
    diameter: 120,
    distance_from_sun: 180,
    luas: 146,
    temp: -139,
    color: '/textures/saturn.jpg',
    orbital_period: 10759
  },
  {
    id: '8',
    name: 'Urano',
    about: 'Um gigante de gelo que rota de lado, Urano tem um eixo de rotação inclinado em quase 90 graus em relação à sua órbita.',
    texturePath: '/textures/uranus.jpg',
    diameter: 511,
    distance_from_sun: 287,
    luas:27,
    temp: -197 ,
    color: '/textures/uranus.jpg',
    orbital_period: 30687
  },
  {
    id: '9',
    name: 'Sol',
    about: '',
    texturePath: '/textures/sunmap.jpg',
    diameter: 0,
    distance_from_sun: 0,
    luas:0,
    temp: 0 ,
    color: '/textures/sunmap.jpg',
    orbital_period: 0
  },
];

export default planetsData;
